trigger:
  - main # production
  - develop # test

resources:
  repositories:
    - repository: templates
      type: github
      name: ProovGroup/ci-templates-azure
      endpoint: ProovGroup

variables:
  - group: PASSWORDS
  - group: GO_CONFIG
  - name: buildEnvironment
    ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      value: "test"
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: "production"
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: "production"

  - name: awsEnvironment
    ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      value: "AWS - TEST"
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: "AWS - PRODUCTION"
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: "AWS - PRODUCTION"

  - name: awsRoleArn
    ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      value: "worker-report-document-linker"
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: "worker-report-document-linker"
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: "worker-report-document-linker"

  - name: vmImageName
    value: "ubuntu-latest"

  - name: serviceName
    value: "worker-report-document-linker"

  - name: awsRegion
    value: "eu-west-1"

  - name: Runtime
    value: "provided.al2023"

  - name: goversion
    value: "1.22.1"

  - name: working_dir
    value: "$(System.DefaultWorkingDirectory)"

parameters:
  - name: runTerraform
    displayName: "runTerraform"
    type: boolean
    default: false
  - name: withConf
    displayName: "runWithConf"
    type: boolean
    default: false
  - name: withAssets
    displayName: "runWithAssets"
    type: boolean
    default: false
  - name: runtime2023
    displayName: "runtime2023"
    type: boolean
    default: true
    
stages:
  - stage:
    displayName: 'Build package by runtime'
    jobs:
    - job:
      steps:
        - template: stage-al2023-configuration.yml@templates
          parameters:
            service_name: $(serviceName)
            environment: $(buildEnvironment)
            working_dir: $(working_dir)
            runtime: $(Runtime)
            go_version: $(goversion)
  - stage: DeployAWS
    displayName: 'Deploy to AWS environment'
    jobs:
    - job:
      steps:
        - template: task-deploy-lambda-2023.yml@templates
          parameters:
            service_name: $(serviceName)
            environment: $(buildEnvironment)
            aws_region: $(awsRegion)
            aws_environment: $(awsEnvironment)
            aws_role_arn: $(awsRoleArn)
        - template: task-update-lambda-alias.yml@templates
          parameters:
            service_name: $(serviceName)
            environment: $(buildEnvironment)
            aws_region: $(awsRegion)
            aws_environment: $(awsEnvironment)
            lambda_version: $(deployedLambda)
